### PR TITLE
Added support for symbols

### PR DESCRIPTION
**Pull request by tk8817**
Hi @cheezy I have added support for symbols, including a new test cases & supporting step defenition

### CODE REVIEW

**Comment by cheezy** [comment]
Looks like you removed a dependency in gemspec.  If you add it back I will merge this pr and make a new release.

**Comment by tk8817** [comment]
@cheezy ack! sorry about that, I removed the dependency later on so I could use my personal yml-reader repo to have multi-file support

**Comment by cheezy** [comment]
Looks like the build failed.

**Comment by tk8817** [comment]
Ive been going through it - it fails for the new yml_reader 0.7 release (my code none the less!)
```ruby   
def load(filename)
    files= filename.include?(',') ? filename.split(',') : [filename]
    @yml = files.inject({}) do |total_merge,file|
      total_merge.merge!(::YAML.load(ERB.new(File.read("#{yml_directory}/#{file}")).result(binding)))
    end
  end
```

The build passes on yml_reader 0.6 (let me rebuild with 0.6 as a locked dependency)

**Comment by cheezy** [comment]
What is the issue with he yml_reader update?

**Comment by tk8817** [comment]
Build passing without the multi-file support in yml_reader. I will look into the error, for now - fig_newton is safe to push.

**Comment by tk8817** [comment]
FYI this is the error from Travis when running against yml_reader 0.7 (multi-file). 

```ruby
  1) FigNewton when asking for data should retrieve the data by a key named after the method called
     Failure/Error: FigNewton.load('test')
     
     TypeError:
       no implicit conversion of RSpec::Mocks::Double into Hash
     # /home/travis/.rvm/gems/ruby-2.0.0-p647-clang/gems/yml_reader-0.7/lib/yml_reader.rb:32:in `merge!'
     # /home/travis/.rvm/gems/ruby-2.0.0-p647-clang/gems/yml_reader-0.7/lib/yml_reader.rb:32:in `block in load'
     # /home/travis/.rvm/gems/ruby-2.0.0-p647-clang/gems/yml_reader-0.7/lib/yml_reader.rb:31:in `each'
     # /home/travis/.rvm/gems/ruby-2.0.0-p647-clang/gems/yml_reader-0.7/lib/yml_reader.rb:31:in `inject'
     # /home/travis/.rvm/gems/ruby-2.0.0-p647-clang/gems/yml_reader-0.7/lib/yml_reader.rb:31:in `load'
     # ./spec/fig_newton/fig_newton_spec.rb:11:in `block (3 levels) in <top (required)>'
 1/1 |===== 100 ======>| Time: 00:00:00 
```

**Comment by tk8817** [comment]
Alright this makes sense as a failure - either the test needs to be updated or I can update how the YAML is merged. As it stands the the inject passes an empty Hash as the first result the merged data is built on that.

**Comment by cheezy** [comment]
Let's update the test.

**Comment by tk8817** [comment]
Abandoning this PR, and opening a new one with updated branch.

**Pull request closed without merging**
